plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\u05059322\\OneDrive - University of Pretoria\\Acer\\My User Documents\\Side Projects\\AiForm Studio\\NYAUTSA SS TRADING\\nyautsa-website\\nyautsa-website"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]